# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-02 10:43
from __future__ import unicode_literals

import administration.models
import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCottage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField()),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('status', models.TextField(default='available')),
                ('name', models.TextField(blank=True, null=True)),
                ('mobilenumber', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('gstno', models.TextField(blank=True, null=True)),
                ('companyname', models.TextField(blank=True, null=True)),
                ('companyaddress', models.TextField(blank=True, null=True)),
                ('roomprice', models.IntegerField(blank=True, null=True)),
                ('gst', models.IntegerField(blank=True, null=True)),
                ('ccavenue', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('paymentstatus', models.TextField(default='pending')),
                ('nights', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/ubuntu/Desktop/homa/media'), upload_to=administration.models.upload_location)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, default='all', null=True)),
                ('page', models.TextField()),
                ('source', models.TextField(blank=True, null=True)),
                ('source_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CelebritySchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('at', models.DateTimeField()),
                ('language', models.TextField(blank=True, default='all', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Function_halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.TextField(unique=True)),
                ('material_name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('publish', models.BooleanField(default=False)),
                ('at', models.DateTimeField(default=datetime.datetime(2018, 8, 2, 16, 13, 16, 922693))),
            ],
        ),
        migrations.CreateModel(
            name='Purohits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.TextField(unique=True)),
                ('purohit_name', models.TextField(blank=True, null=True)),
                ('purohit_mobile_number', models.TextField(unique=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.TextField()),
                ('social_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('mobile_number', models.TextField(unique=True)),
                ('role', models.TextField()),
                ('gender', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('password', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AddField(
            model_name='publicsuggestions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
    ]
