# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-02 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('client_mobile_number', models.TextField()),
                ('client_name', models.TextField(blank=True, null=True)),
                ('event_name', models.TextField()),
                ('event_start_date', models.CharField(blank=True, max_length=50)),
                ('event_end_date', models.CharField(blank=True, max_length=50)),
                ('event_place', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='publicsuggestions',
            name='at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 2, 16, 28, 48, 846789)),
        ),
    ]
