# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-02 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20180802_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequests',
            name='event_end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequests',
            name='event_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequests',
            name='event_start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publicsuggestions',
            name='at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 2, 16, 37, 51, 215255)),
        ),
    ]
