# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-02 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20180802_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignThingsToEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50)),
                ('client_number', models.TextField()),
                ('p_id', models.TextField(blank=True, null=True)),
                ('purohit_name', models.TextField(blank=True, null=True)),
                ('purohit_mobile_number', models.TextField(blank=True, null=True)),
                ('m_id', models.TextField(blank=True, null=True)),
                ('material_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publicsuggestions',
            name='at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 2, 16, 47, 54, 377053)),
        ),
    ]
