# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-02 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20180802_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicsuggestions',
            name='at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 2, 16, 52, 36, 975153)),
        ),
    ]
